apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/toleksa/kube-system.git
    path: example-guestbook
    targetRevision: HEAD
