grafana:
  adminPassword: prom-operator

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    hosts: 
    - prometheus.kube2.ac
grafana:
  ingress:
    enabled: true
    hosts: 
    - grafana.kube2.ac
