apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '4.9.12'
    chart: argo-cd
    helm:
      values: |
        dex:
          enabled: false
        server:
          #extraArgs:
          #- --tlsminversion "1.2"
          #  - --insecure
          {{- if .Values.argocd.server.ingress.enabled }}
          ingress:
            enabled: true
            https: true
            tls:
            - hosts:
              - "argocd.{{ .Values.domain }}"
              secretName: argocd-cert
            hosts:
            - "argocd.{{ .Values.domain }}"
            annotations:
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          {{- end }}
        config:
          repositories: |
            - type: helm
              name: stable
              url: https://charts.helm.sh/stable
            - type: helm
              name: argo-cd
              url: https://argoproj.github.io/argo-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
