apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  annotations:
    #argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-9"
spec:
  destinations:
  - namespace: argocd
    server: '*'
  - namespace: elk
    server: '*'
  - namespace: external-dns
    server: '*'
  - namespace: kube-system
    server: '*'
  - namespace: longhorn-system
    server: '*'
  - namespace: metallb-system
    server: '*'
  - namespace: monitoring
    server: '*'
  - namespace: istio-system
    server: '*'
  - namespace: neuvector
    server: '*'
  - namespace: kubecost
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://github.com/toleksa/kube-system'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://charts.longhorn.io'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://github.com/prometheus-community/helm-charts'
  - 'https://helm.elastic.co'
  - 'https://github.com/istio/istio.git'
  - 'https://neuvector.github.io/neuvector-helm/'
  - 'https://kubecost.github.io/cost-analyzer/'
