apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  destinations:
  - namespace: argocd
    server: '*'
  - namespace: external-dns
    server: '*'
  - namespace: kube-system
    server: '*'
  - namespace: longhorn-system
    server: '*'
  - namespace: metallb-system
    server: '*'
  - namespace: monitoring
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://github.com/toleksa/kube-system'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://charts.longhorn.io'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://github.com/prometheus-community/helm-charts'
