apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '3.33.5'
    chart: argo-cd
    helm:
      values: |
        dex:
          enabled: false
        server:
          extraArgs:
            - --insecure
          {{- if .Values.argocd.server.ingress.enabled }}
          ingress:
            enabled: true
            https: false
            hosts:
            - "argocd.{{ .Values.domain }}"
          {{- end }}
        config:
          repositories: |
            - type: helm
              name: stable
              url: https://charts.helm.sh/stable
            - type: helm
              name: argo-cd
              url: https://argoproj.github.io/argo-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
