{{- if .Values.elk.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: argocd
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: elasticsearch
    targetRevision: 19.4.0
    helm:
      values: |
        global:
          storageClass: longhorn
        master:
          heapSize: 512m
          replicaCount: 1
        coordinating:
          heapSize: 128m
          replicaCount: 1
        ingest:
          heapSize: 128m
          replicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
