{{- if .Values.externaldns.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  project: argocd
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: external-dns
    targetRevision: 6.14.0
    helm:
      values: |
        #sources: {{ .Values.externaldns.sources | default (list "ingress") }}
        sources:
          - ingress
          - istio-virtualservice
          - istio-gateway
        provider: rfc2136
        rfc2136:
          host: {{ .Values.externaldns.rfc2136.host }}
          port: 53
          zone: {{ .Values.externaldns.rfc2136.zone }}
          tsigSecret: {{ .Values.externaldns.rfc2136.tsigSecret }}
          tsigSecretAlg: hmac-sha256
          tsigKeyname: externaldns-key
          tsigAxfr: true
        #domainFilters: [{{ .Values.domain }}]
        serviceAccount: 
          create: true
          name: external-dns
        metrics:
          enabled: {{ .Values.externaldns.metrics | default "false" }} 
          serviceMonitor:
            enabled: {{ .Values.externaldns.metrics | default "false" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
