{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd
  source:
    path: manifests/charts/istio-control/istio-discovery
    repoURL: https://github.com/istio/istio.git
    targetRevision: HEAD
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
{{- end }}
