{{- if .Values.kubecost.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubecost
  project: argocd
  source:
    repoURL: 'https://kubecost.github.io/cost-analyzer/'
    chart: cost-analyzer
    targetRevision: 1.108.1
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
          - "kubecost.{{ .Values.domain}}"
        prometheus:
          nodeExporter:
            service:
              hostPort: 9101
              servicePort: 9101
        grafana:
          ingress:
            enabled: true
            hosts:
            - "grafana.kubecost.{{ .Values.domain}}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
