{{- if .Values.neuvector.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubecost
  project: argocd
  source:
    repoURL: 'https://kubecost.github.io/cost-analyzer/'
    chart: cost-analyzer
    targetRevision: 1.108
    helm:
      values: |
        k3s:
          enabled: true
        controller:
          replicas: 1
        cve:
          scanner:
            replicas: 1
        manager:
          svc:
            type: ClusterIP
          ingress:
            enabled: true
            host: "neuvector.{{ .Values.domain}}"
            annotations:
              #cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            tls: true
            #secretName: neuvector-tls-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
