{{- if .Values.kubecost.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  annotations:
    #argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubecost
  project: argocd
  source:
    repoURL: 'https://kubecost.github.io/cost-analyzer/'
    chart: cost-analyzer
    targetRevision: 1.108.1
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
          - "kubecost.{{ .Values.domain}}"
        persistentVolume:
          size: 5Gi
          dbSize: 5Gi
        prometheus:
          nodeExporter:
            service:
              hostPort: 9101
              servicePort: 9101
          server:
            persistentVolume:
              size: 5Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
