{{- if and (.Values.elk.enabled) (.Values.elk.logstash) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: argocd
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: logstash
    targetRevision: 5.1.2
    helm:
      values: |
        input: |-
          beats { port => 5044 }
        output: |-
          elasticsearch {
            hosts => ["elasticsearch.elk.svc.cluster.local:9200"]
            manage_template => false
            index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
          }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
