apiVersion: metallb.io/v1beta1
kind: IPAddressPool
{{- with (index .Values.metallb.pools 0) }}
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: "metallb-pool-{{ .name }}"
  namespace: metallb-system
spec:
  addresses:
  {{- range .addresses }}
  - {{ . }}
  {{- end }}
  autoAssign: {{ .autoAssign | default "true" }}
  avoidBuggyIPs: {{ .avoidBuggyIPs | default "true" }}
{{- end }}
