apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: metallb
    targetRevision: 2.5.6
    helm:
      values: |
        configInline:
          address-pools:
            {{- toYaml .Values.metallb.pools | nindent 10}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true

