{{- if .Values.metallb.pools }}
  {{- range .Values.metallb.pools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-6"
  name: "{{ .name }}"
  namespace: metallb-system
spec:
  addresses:
    {{- range .addresses }}
  -   {{ . }}
    {{- end }}
  autoAssign: {{ .autoAssign | default "true" }}
  avoidBuggyIPs: {{ .avoidBuggyIPs | default "true" }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-6"
  name: "{{ .name }}"
  namespace: metallb-system
spec:
  ipAddressPools:
  - "{{ .name }}"
  #nodeSelectors:
  #- matchLabels:
  #    kubernetes.io/os: linux
  {{- end }}
{{- end }}

