apiVersion: metallb.io/v1beta1
kind: IPAddressPool
{{- with (index .Values.metallb.pools 0) }}
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec:
  addresses:
  - {{ .addresses[0] }}
{{- end }}
