apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  name: "metallb-pool-{{ .name }}"
  namespace: metallb-system
spec:
  {{- if .addresses }}
  {{- with (index .Values.metallb.pools 0) }}
  addresses:
    {{- range .addresses }}
  - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
  autoAssign: {{ .autoAssign | default "true" }}
  avoidBuggyIPs: {{ .avoidBuggyIPs | default "true" }}
