apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  project: argocd
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: metallb
    targetRevision: 4.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true

