{{- if .Values.elk.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: argocd
  source:
    repoURL: 'https://helm.elastic.co'
    chart: metricbeat
    targetRevision: 7.17.3
    helm:
      values: |
        deployment:
          metricbeatConfig:
            metricbeat.yml: |
              metricbeat.modules:
              - module: kubernetes
                enabled: true
                metricsets:
                  - node
                  - deployment
                  - replicaset
                  - pod
                  - container
                  - system
                  - volume
                period: 10s
                host: ${NODE_NAME}
                hosts: ["https://${NODE_NAME}:10250"]
              setup.kibana:
                host: "kibana.elk.svc.cluster.local:5601"
              output.logstash:
                enabled: true
                hosts: ["logstash.elk.svc.cluster.local:5044"]
              output.elasticsearch:
                enabled: false
                hosts: '["elasticsearch-master-hl:9200}"]'
              #  #username: '${ELASTICSEARCH_USERNAME}'
              #  #password: '${ELASTICSEARCH_PASSWORD}'
              #  ssl.enabled: false
              #  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
              processors:
                - add_kubernetes_metadata: ~
              logging.level: info
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
