{{- if and (.Values.elk.enabled) (.Values.elk.metricbeat) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: argocd
  source:
    repoURL: 'https://helm.elastic.co'
    chart: metricbeat
    targetRevision: 7.17.3
    helm:
      values: |
        daemonset:
          enabled: true
          extraEnvs:
          - name: NODE_NAME
            value: 192.168.0.118
        #    valueFrom:
        #      fieldRef:
        #        fieldPath: spec.nodeName
          - name: ELASTICSEARCH_HOSTS
            value: elasticsearch-master-hl.elk.svc.cluster.local:9200
          metricbeatConfig:
            metricbeat.yml: |
              metricbeat.modules:
              - module: kubernetes
                enabled: true
                metricsets:
                  - container
                  - node
                  - pod
                  - system
                  - volume
                period: 10s
                host: "${NODE_NAME}"
                hosts: ["https://${NODE_NAME}:10250"]
                #host: 192.168.0.118
                #hosts: ["https://192.168.0.118:10250"]
                bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                ssl.verification_mode: "none"
                processors:
                - add_kubernetes_metadata: ~
              - module: kubernetes
                enabled: true
                metricsets:
                  - event
              - module: system
                period: 10s
                metricsets:
                  - cpu
                  - load
                  - memory
                  - network
                  - process
                  - process_summary
                processes: ['.*']
                process.include_top_n:
                  by_cpu: 5
                  by_memory: 5
              - module: system
                period: 1m
                metricsets:
                  - filesystem
                  - fsstat
                processors:
                - drop_event.when.regexp:
                    system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
              setup.kibana:
                host: "kibana.elk.svc.cluster.local:5601"
              output.logstash:
                enabled: false
                #hosts: ["logstash.elk.svc.cluster.local:5044"]
              output.elasticsearch:
                enabled: true
                hosts: '["https://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}"]'
                #hosts: ["elasticsearch-master-hl.elk.svc.cluster.local:9200"]
                ssl.enabled: false
                #ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
                #username: '${ELASTICSEARCH_USERNAME}'
                #password: '${ELASTICSEARCH_PASSWORD}'
        deployment:
          enabled: true
          extraEnvs:
          - name: NODE_NAME
            value: 192.168.0.118
        #    valueFrom:
        #      fieldRef:
        #        fieldPath: spec.nodeName
          - name: ELASTICSEARCH_HOSTS
            value: elasticsearch-master-hl.elk.svc.cluster.local:9200
          metricbeatConfig:
            metricbeat.yml: |
              metricbeat.modules:
              - module: kubernetes
                enabled: true
                metricsets:
                  - state_node
                  - state_deployment
                  - state_replicaset
                  - state_pod
                  - state_container
                period: 10s
                hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
              output.elasticsearch:
                #hosts: '["https://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}"]'
                hosts: ["elasticsearch-master-hl.elk.svc.cluster.local:9200"]
                #username: '${ELASTICSEARCH_USERNAME}'
                #password: '${ELASTICSEARCH_PASSWORD}'
                ssl.enabled: false
                #ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}

