{{- if .Values.elk.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  project: argocd
  source:
    repoURL: 'https://helm.elastic.co'
    chart: metricbeat
    targetRevision: 
    helm:
      values: |
        deployment:
          metricbeatConfig:
            metricbeat.yml: |
              metricbeat.modules:
              - module: kubernetes
                enabled: true
                metricsets:
                  - state_node
                  - state_deployment
                  - state_replicaset
                  - state_pod
                  - state_container
                period: 10s
                hosts: ["https://127.0.0.1:10250"]
              setup.kibana:
								host: "kibana.elk.svc.cluster.local:5601"
							output.logstash:
								hosts: ["logstash.elk.svc.cluster.local:5044"]
				      #output.elasticsearch:
				      #  hosts: '["elasticsearch.elk.svc.cluster.local:9200}"]'
				      #  #username: '${ELASTICSEARCH_USERNAME}'
				      #  #password: '${ELASTICSEARCH_PASSWORD}'
				      #  ssl.enabled: false
				      #  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
							processors:
							  - add_kubernetes_metadata: ~
							logging.level: error
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
{{- end }}
