apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-main
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/kube-system'
    targetRevision: HEAD
    path: 'argocd'
    helm:
      values: |
        domain: example.com

        argocd:
          dex:
            enabled: false
          server:
            ingress:
              enabled: true
              https: true

        externaldns:
          enabled: false
          rfc2136:
            host: 127.0.0.1
            zone: example.com
            tsigSecret: ""

        metallb:
          pools:
          - name: default
            protocol: layer2
            addresses:
            - 127.0.0.1-127.0.0.1
            avoid-buggy-ips: true

        kubecost:
          enabled: false
        neuvector:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
