domain: example.com

longhorn:
  defaultClassReplicaCount: 1
  ingress:
    enabled: false

argocd:
  installCRDs: false
  global:
    image:
      tag: v2.1.3
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      https: true
      hosts:
      - argocd.example.com
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

externaldns:
  rfc2136:
    host: 127.0.0.1
    zone: example.com
    tsigSecret: ""

metallb:
  pools:
  - name: default
    protocol: layer2
    addresses:
    - 127.0.0.1-127.0.0.1
    avoid-buggy-ips: true


